# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giving.Charity')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giving.Donor')),
            ],
        ),
    ]
